### ISSUE TITLE
PHP 8.2 and PHPStan tracking

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/localgov_project#133]
This issue will track and link to individual module tickets that require PHP 8.2 fixes as well as fixes related to a recent change to PHPStan level to match Drupal core in https://github.com/localgovdrupal/localgov_project/pull/131

- [x] [localgov_alert_banner](https://github.com/localgovdrupal/localgov_alert_banner/issues/287) - (https://github.com/localgovdrupal/localgov_alert_banner/pull/288)
- [x] [localgov_directories](https://github.com/localgovdrupal/localgov_directories/issues/315) - (https://github.com/localgovdrupal/localgov_directories/pull/316)
- [x] [localgov_guides](https://github.com/localgovdrupal/localgov_guides/issues/127) - (https://github.com/localgovdrupal/localgov_guides/pull/130)
- [x] [localgov_menu_link_group](https://github.com/localgovdrupal/localgov_menu_link_group/issues/28) - (https://github.com/localgovdrupal/localgov_menu_link_group/pull/29)
- [x] [localgov_news](https://github.com/localgovdrupal/localgov_news/issues/96) - (https://github.com/localgovdrupal/localgov_news/pull/97)
- [x] [localgov_openreferral](https://github.com/localgovdrupal/localgov_openreferral/issues/47) - (https://github.com/localgovdrupal/localgov_openreferral/pull/48)
- [x] [localgov_page_components](https://github.com/localgovdrupal/localgov_page_components/issues/41) - (https://github.com/localgovdrupal/localgov_page_components/pull/42)
- [x] [localgov_services](https://github.com/localgovdrupal/localgov_services/issues/224) - (https://github.com/localgovdrupal/localgov_services/pull/225)
- [x] localgov_step_by_step - fixed by [@Adnan-cds](https://github.com/localgovdrupal/localgov_step_by_step/pull/89) needs release 
- [x] [localgov_subsites](https://github.com/localgovdrupal/localgov_subsites/issues/127) - (some issues already fixed by @Adnan-cds the rest in https://github.com/localgovdrupal/localgov_subsites/pull/128)
- [x] [localgov_workflows](https://github.com/localgovdrupal/localgov_workflows/issues/67) - (https://github.com/localgovdrupal/localgov_workflows/pull/68)
- [x] [localgov_base](https://github.com/localgovdrupal/localgov_base/issues/482) - (https://github.com/localgovdrupal/localgov_base/pull/485)

**Comment by millnut** [comment]
@finnlewis @Adnan-cds all of the LocalGov Drupal code above now has PRs for PHP 8.2 compatibility and/or needs a release. I have tested all these locally by running the project and then installing the demo module to check for deprecations. @Adnan-cds, if you spot any more PHP 8.2 deprecations, please let me know.

Once each has been merged and then releases created for each module I should be able to test the project workflows again once https://github.com/localgovdrupal/localgov_project/pull/130 and https://github.com/localgovdrupal/localgov_project/pull/131 are merged.

There are some deprecations on contrib modules in PHP 8.2 that we depend on such as [Pathauto](https://www.drupal.org/project/pathauto/issues/3388122) and [Entity Browser](https://www.drupal.org/project/entity_browser/issues/3350169) but I would rather they create new releases than add a patch within LocalGov Drupal.

Once this is complete, I can look into the Microsites project and check what PHP 8.2 deprecations might be there.

**Comment by finnlewis** [comment]
Amazing, thanks @millnut 

Closing this.
